### ISSUE TITLE
Mapping Netbox sites/location to areas/buildings/floors in DNAC

### ISSUE THREAD

**Issue by christianahug** [robertcsapo/ciscodnacnetbox#11]
Is there a way to correctly map areas/buildings/floors to sites and locations in Netbox? We already have a structure in Netbox in place and would like to sync devices from one of our sites from DNAC to Netbox. Unfortunately, we run into the problem of the plugin automatically generating sites based on DNAC (e.g. new site = Global/Building/Floor when in Netbox the correct mapping would be area = site, building = location, floor = child location) instead of using the structure present in Netbox.

**Comment by robertcsapo** [comment]
@christianahug you are correct. this plugins uses the Cisco DNA Center as the source of truth for the location/site hierarchy.
Otherwise, there would be two different source of truth.
