### ISSUE TITLE
Netbox 3.4.1, DNAC 2.3.3.6 - Sync Failure

### ISSUE THREAD

**Issue by ghost** [robertcsapo/ciscodnacnetbox#13]
I was able to integrate the plugin, but it seems that after initially polling a few devices I'm hitting a timeout. Could anyone help me understand what might be causing this? I've attached a screenshot of the exact error. So far I've tried a fresh install of Netbox and uninstalling/reinstalling the plugin. Could this be due to the plugin not supporting Netbox v3.4.1? 

![2022-12-29 09_27_01-](https://user-images.githubusercontent.com/114808789/209974495-5d7ffe6d-e09b-4e79-a141-1a8fce9cf074.png)

**Comment by ghost** [comment]
I should add we have several thousand locations and access points. Perhaps there's a timeout value that is being hit before everything is finished polling?

**Comment by robertcsapo** [comment]
504 looks like an issues on the Cisco DNA Center side.
Could you try to disable and enable the Cisco DNA Center API again under the platform settings?
