### ISSUE TITLE
can't run ciscodnacnetbox on NetBox 3.5.4

### ISSUE THREAD

**Issue by DavoodFadaee** [robertcsapo/ciscodnacnetbox#17]
Hi,
i installed cisco dnac netbox plugin based on instructions but it didn't work and Netbox stoped and couldn't run.
OS: Ubuntu 22
Netbox version : 3.5.4
is it possible to guide me solve this problem?

**Comment by robertcsapo** [comment]
NetBox release 3.4 requires code change.

Related to #16

**Comment by cloudcapps** [comment]
> NetBox release 3.4 requires code change.
> 
> Related to #16

Any plans to update this plugin to work with Netbox 3.6.x?

Thank you

**Comment by robertcsapo** [comment]
This has been patched in the latest release now
```pip install ciscodnacnetbox==3.5.0```

**Comment by robertcsapo** [comment]
@cloudcapps I haven't tested 3.6 yet with v3.5.0, can you open a new issue?
