### ISSUE TITLE
Adding DNaCenter to Netbox Fails with the Following Issue

### ISSUE THREAD

**Issue by mwalton42** [robertcsapo/ciscodnacnetbox#18]
After filling out the info on the plugin configuration page I am getting the following error.  Netbox itself is running fine but unable to configure our DNAC instance.    

Server Error
A database programming error was detected while processing this request. Common causes include the following:

Database migrations missing - When upgrading to a new NetBox release, the upgrade script must be run to apply any new database migrations. You can run migrations manually by executing python3 manage.py migrate from the command line.

Unsupported PostgreSQL version - Ensure that PostgreSQL version 10 or later is in use. You can check this by connecting to the database using NetBox's credentials and issuing a query for SELECT VERSION().

The complete exception is provided below:

<class 'django.db.utils.ProgrammingError'>

column "created" of relation "ciscodnacnetbox_settings" does not exist
LINE 1: INSERT INTO "ciscodnacnetbox_settings" ("created", "last_upd...
                                                ^

Python version: 3.10.12
NetBox version: 3.2.1
If further assistance is required, please post to the [NetBox discussion forum](https://github.com/netbox-community/netbox/discussions) on GitHub.

**Comment by robertcsapo** [comment]
Did you run the database migration?
```
(venv) $ cd /opt/netbox/netbox/
(venv) $ python3 manage.py migrate
```

https://docs.netbox.dev/en/stable/plugins/

**Comment by mwalton42** [comment]
Hello Robert,

I did do that.   I also ran python3 manage.py makemigratitions as the manage.py migrate suggested but ended with this error still.

(venv) ***@***.***:/opt/netbox/netbox# python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, circuits, ciscodnacnetbox, contenttypes, core, dcim, django_rq, extras, ipam, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wireless
Running migrations:
  No migrations to apply.
  Your models in app(s): 'ciscodnacnetbox' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(venv) ***@***.***:/opt/netbox/netbox# python3 manage.py makemigrations
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions
[https://opengraph.githubassets.com/90c1e74784ac451ccf7b5ec0e8232b3e18d52f2db313b9282819fd62ccc602da/netbox-community/netbox]<https://github.com/netbox-community/netbox/discussions>
netbox-community netbox · Discussions<https://github.com/netbox-community/netbox/discussions>
Explore the GitHub Discussions forum for netbox-community netbox. Discuss code, ask questions & collaborate with the developer community.
github.com


Still having this issue.  Tried to update to latest ubuntu updates and also latest netbox 3.7.7 and latest dnac plugin.     But still get the previous error with DB.   its almost like the info never got put in db in first place.

Sincerely,

Michael Walton
Senior Network Engineer, Global Evangelism Inc.
(210) 490 1600
________________________________
