### ISSUE TITLE
Prime - DNAC

### ISSUE THREAD

**Issue by andershagman** [robertcsapo/ciscodnacnetbox#3]
Hi
We use Prime to collect devices today. It creates device types and devices with interfaces and IP addresses. Sites are handled in Netbox. As many we plan to move to DNAC one day.

One question is, as you sync sites from DNAC, how do you differ the site definition in Netbox from the definition in DNAC? In Netbox it's more of a organization thing and in DNAC a site is an area, building or floor. Closest for me is area. 

Another thing is, if Netbox is the single source of truth, how do you handle conflicts? We allow addition  from Prime but not deletion to ensure a correct offline documentation.

**Comment by robertcsapo** [comment]
Hey

* Sites are synced based on tenant feature in NetBox. In this case, every Cisco DNA Center is a tenant. [Screenshot](https://github.com/robertcsapo/ciscodnacnetbox/raw/main/img/sites.png)
  * NetBox still wants Site Names to be unique
    * Example: Global isn't unique in every DNAC and it's added with SiteID prefix from DNAC.
  * Site Name is always **Global**/Area/Building/Floor or **Global**/Building/Floor from DNAC
    *  Prime Infra uses System Campus.


 * Conflicts for **Sites** would be if some other system uses same Site Name prefix as above (Global/Area/Building/Floor), that would cause conflict with unique Site Names in NetBox.
   * https://github.com/robertcsapo/ciscodnacnetbox/blob/0a33f2eb1f5ca064b2c1d1e583b37ddd5e432eeb/ciscodnacnetbox/ciscodnac/netbox.py#L91
   * In every full sync, the plugin also purges old data (to be i sync with DNAC)
   * https://github.com/robertcsapo/ciscodnacnetbox/blob/4dfa6a2f63444c74c5fb3daf88997a60b2edf5ad/ciscodnacnetbox/ciscodnac/data.py#L27
     * If it differs from NetBox and DNAC, then it deletes the sites/devices in NetBox.
     * https://github.com/robertcsapo/ciscodnacnetbox/blob/4dfa6a2f63444c74c5fb3daf88997a60b2edf5ad/ciscodnacnetbox/ciscodnac/netbox.py#L353 


 * Conflicts with devices is based on serial number. If the serial number exist, it only updates the data.
   * https://github.com/robertcsapo/ciscodnacnetbox/blob/4dfa6a2f63444c74c5fb3daf88997a60b2edf5ad/ciscodnacnetbox/ciscodnac/netbox.py#L212

Unfortunately, putting objects in Tenants doesn't enable overlapping values in some areas of NetBox database.
